name: Deploy New Docker Containerrr

on:
  push:
    branches:
      - master

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy-container:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up the SSH key for server connection
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # Step 3: Add server public key to known_hosts
      - name: Add server public key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Step 4: SSH into the server and perform deployment
      - name: Deploy on the server
        run: |
          ssh -T -i private_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Set up environment variables
            export COMMIT_ID=$(git -C /home/ubuntu/your-app-repo rev-parse --short HEAD)

            # Stop and remove the old container if it exists
            if docker ps -a --filter "name=php-app" --format '{{.Names}}' | grep -q '^php-app$'; then
              docker commit php-app old-php-app:backup-\$(date +'%Y%m%d%H%M%S')
              docker tag old-php-app:backup-\$(date +'%Y%m%d%H%M%S') ${{ secrets.DOCKER_USERNAME }}/php-app:backup-\$(date +'%Y%m%d%H%M%S')
              docker push ${{ secrets.DOCKER_USERNAME }}/php-app:backup-\$(date +'%Y%m%d%H%M%S')
              docker stop php-app
              docker rm php-app
            fi

            # Remove old Docker images
            docker images --filter=reference="php-app" --format "{{.ID}}" | xargs -r docker rmi -f

            # Pull the latest changes from the repository
            cd /home/ubuntu/your-app-repo
            git pull origin main

            # Build the new Docker image with the commit ID
            docker build -t php-app:\$COMMIT_ID -t php-app:latest .

            # Push the new image to DockerHub
            docker tag php-app:\$COMMIT_ID ${{ secrets.DOCKER_USERNAME }}/php-app:\$COMMIT_ID
            docker tag php-app:latest ${{ secrets.DOCKER_USERNAME }}/php-app:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/php-app:\$COMMIT_ID
            docker push ${{ secrets.DOCKER_USERNAME }}/php-app:latest

            # Run the new container
            docker run -d --name php-app -p 9001:9001 php-app:latest
          EOF

      # Step 5: Clean up SSH private key
      - name: Clean up SSH private key
        run: |
          rm -f private_key.pem
        if: always()

      # Step 6: Clean up known_hosts file
      - name: Clean up known_hosts file
        run: |
          rm -f ~/.ssh/known_hosts
        if: always()
